---
# handlers file for vault

- name: start vault
  service:
    name: vault
    state: started

- name: stop vault
  service:
    name: vault
    state: stopped

- name: restart vault
  service:
    name: vault
    state: restarted

- name: reload vault
  service:
    name: vault
    state: reloaded
